---
- name: Create and manage directory
  hosts: all
  tasks: 
  
  - name: Create a directory if it does not exist
    file:
      path: /home/ec2-user/test-directory
      state: directory
      
  - name: Create a file if it does not exist
    file: 
      path: /home/ec2-user/test-directory/test.txt
      state: touch
